### ISSUE TITLE
Run 'MPC_Thread' way will cause fall?

### ISSUE THREAD

**Issue by littleggghost** [modulabs/gdyn-legged-locomotion#7]
The robot cannot keep balance with this threaded way, could you fix this?

**Comment by elton-choi** [comment]
Hmm, one of our member fixed this issue with 4 foots on ground, 
but there is still a issue with 3 foots on ground.
I assume there is some bug when we factorizing matrix in MPC with foots on ground.

**Comment by littleggghost** [comment]
Thanks for your reply. I will keep watching your new progress!
